// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EntriesDefault struct {
	ID           int64              `json:"id"`
	Type         string             `json:"type"`
	TraceID      pgtype.UUID        `json:"trace_id"`
	SpanID       pgtype.UUID        `json:"span_id"`
	ParentSpanID pgtype.UUID        `json:"parent_span_id"`
	Service      string             `json:"service"`
	Level        pgtype.Text        `json:"level"`
	Status       pgtype.Text        `json:"status"`
	SpanName     pgtype.Text        `json:"span_name"`
	Message      pgtype.Text        `json:"message"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID           int64              `json:"id"`
	Type         string             `json:"type"`
	TraceID      pgtype.UUID        `json:"trace_id"`
	SpanID       pgtype.UUID        `json:"span_id"`
	ParentSpanID pgtype.UUID        `json:"parent_span_id"`
	Service      string             `json:"service"`
	Level        pgtype.Text        `json:"level"`
	Status       pgtype.Text        `json:"status"`
	SpanName     pgtype.Text        `json:"span_name"`
	Message      pgtype.Text        `json:"message"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
