// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntriesByTraceID = `-- name: GetEntriesByTraceID :many
select id, type, trace_id, span_id, parent_span_id, service, level, status, span_name, message, duration_ms, metadata, created_at from entries
where trace_id = $1
order by created_at asc
`

func (q *Queries) GetEntriesByTraceID(ctx context.Context, traceID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Service,
			&i.Level,
			&i.Status,
			&i.SpanName,
			&i.Message,
			&i.DurationMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogs = `-- name: SearchLogs :many
select id, type, trace_id, span_id, parent_span_id, service, level, status, span_name, message, duration_ms, metadata, created_at from entries
where type = 'log'
  and ($1::text is null or service = $1)
  and ($2::text is null or level = $2)
  and ($3::text is null or message ilike '%' || $3 || '%')
  and ($4::timestamptz is null or created_at >= $4)
  and ($5::timestamptz is null or created_at < $5)
  and ($6::bigint is null or id < $6)
order by created_at desc, id desc
limit $7
`

type SearchLogsParams struct {
	Service  pgtype.Text        `json:"service"`
	Level    pgtype.Text        `json:"level"`
	Query    pgtype.Text        `json:"query"`
	From     pgtype.Timestamptz `json:"from"`
	To       pgtype.Timestamptz `json:"to"`
	BeforeID pgtype.Int8        `json:"before_id"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) SearchLogs(ctx context.Context, arg SearchLogsParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, searchLogs,
		arg.Service,
		arg.Level,
		arg.Query,
		arg.From,
		arg.To,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Service,
			&i.Level,
			&i.Status,
			&i.SpanName,
			&i.Message,
			&i.DurationMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
