apiVersion: v1
kind: ConfigMap
metadata:
    name: log-pipeline-config
    namespace: log-pipeline
data:
    DB_HOST: "log-pipeline-db"
    DB_PORT: "5432"
    DB_NAME: "logpipeline"
    REDIS_ADDR: "log-pipeline-redis:6379"
    INGEST_PORT: "8080"
    QUERY_PORT: "8081"
    INGEST_URL: "http://ingest:8080"
    ORDER_SERVICE_URL: "http://order-service:9001"
    PAYMENT_SERVICE_URL: "http://payment-service:9002"
    INVENTORY_SERVICE_URL: "http://inventory-service:9003"
