apiVersion: v1
kind: Service
metadata:
    name: log-pipeline-redis
    namespace: log-pipeline
spec:
    clusterIP: None
    selector:
        app: redis
    ports:
        - port: 6379
          targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: redis
    namespace: log-pipeline
spec:
    serviceName: log-pipeline-redis
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis:7
                  ports:
                      - containerPort: 6379
                  volumeMounts:
                      - name: redisdata
                        mountPath: /data
                  readinessProbe:
                      exec:
                          command: ["redis-cli", "ping"]
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  livenessProbe:
                      exec:
                          command: ["redis-cli", "ping"]
                      initialDelaySeconds: 10
                      periodSeconds: 10
    volumeClaimTemplates:
        - metadata:
              name: redisdata
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 1Gi
