apiVersion: v1
kind: Secret
metadata:
    name: log-pipeline-secret
    namespace: log-pipeline
type: Opaque
stringData:
    DB_USER: "logpipeline"
    DB_PASSWORD: "REAL_PASSWORD"
    REDIS_PASS: ""
